apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka-service-url: "http://eureka-0.eureka:8761/eureka"

---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: config-cm
  data:
    config-url: "http://config-service-svc"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  hostname: "mysql-0.mysql"

  

